# Description processing with an LLM (Gemini)

In [1]:
 import pandas as pd
df= pd.read_csv("/content/tayara_tn_clean.csv")

In [ ]:
display(df)

,price,transaction,title,city,region,description,surface,bathrooms,rooms
0,490000.0,sale,S+3 avec jardin à chotrana 1,ariana,chotrana 1,Cet appartement est situé au rez-de-chaussée d...,141.0,3.0,3
1,380000.0,sale,un s+2 à chotrana 1,ariana,chotrana 1,Cet appartement est situé à chotrana 1 dans un...,100.0,1.0,2
2,180000.0,sale,S+3 en vente,manouba,manouba ville,Cet appartement se situe à Dyar ben Mahmoud Ag...,130.0,1.0,4
3,240000.0,sale,Charmant S+2 avec grande terrasse à vendre,tunis,gammarth,À vendre : Appartement S+2 avec une grande ter...,120.0,1.0,1
4,365000.0,sale,appartement s3 ennaser bon prix,ariana,ennasr 2,a vendre a ennaser un appartement s3 au 5éme é...,148.0,2.0,03
...,...,...,...,...,...,...,...,...,...
574,339300.0,sale,A VENDRE S+2 SOUKRA,ariana,soukra,Notre agence palmarès immobilière met à la ven...,117.0,1.0,3
575,380000.0,sale,S+2 Sur Plan à La Soukra,ariana,soukra,✅✅Palmarès immobilier met en vente un appartem...,115.0,1.0,2
576,380000.0,sale,S+3 en Vente à Ennasr 2,ariana,ennasr 2,Cet appartement occupe le rez-de-chaussée d'un...,145.0,2.0,3
577,550000.0,sale,S+3 à Vendre à Jardin d'Ennasr,ariana,ennasr,Cet appartement occupe le troisième étage d’un...,176.0,3.0,3
578,310000.0,sale,S+3 en Vente à Ennasr 2,ariana,ennasr 2,Cet appartement est situé au premier étage d'u...,119.0,2.0,3

In [2]:
df_description=df.loc[:,'description']
display(df_description)

0      Cet appartement est situé au rez-de-chaussée d...
1      Cet appartement est situé à chotrana 1 dans un...
2      Cet appartement se situe à Dyar ben Mahmoud Ag...
3      À vendre : Appartement S+2 avec une grande ter...
4      a vendre a ennaser un appartement s3 au 5éme é...
                             ...
574    Notre agence palmarès immobilière met à la ven...
575    ✅✅Palmarès immobilier met en vente un appartem...
576    Cet appartement occupe le rez-de-chaussée d'un...
577    Cet appartement occupe le troisième étage d’un...
578    Cet appartement est situé au premier étage d'u...
Name: description, Length: 579, dtype: object

Translate description into english language

In [ ]:
! pip install googletrans==4.0.0-rc1

Requirement already satisfied: googletrans==4.0.0-rc1 in /usr/local/lib/python3.11/dist-packages (4.0.0rc1)
Collecting httpx==0.13.3 (from googletrans==4.0.0-rc1)
  Using cached httpx-0.13.3-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2024.12.14)
Requirement already satisfied: hstspreload in /usr/local/lib/python3.11/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2025.1.1)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (1.3.1)
Requirement already satisfied: chardet==3.* in /usr/local/lib/python3.11/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (3.0.4)
Requirement already satisfied: idna==2.* in /usr/local/lib/python3.11/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2.10)
Requirement already satisfied: rfc3986<2,>=1.3 in /usr/local/lib/python3.11/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (1.5.0)
Collecting httpcore==0.9.* (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Using cached httpcore-0.9.1-py3-none-any.whl.metadata (4.6 kB)
Collecting h11<0.10,>=0.8 (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1)
  Using cached h11-0.9.0-py2.py3-none-any.whl.metadata (8.1 kB)
Requirement already satisfied: h2==3.* in /usr/local/lib/python3.11/dist-packages (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (3.2.0)
Requirement already satisfied: hyperframe<6,>=5.2.0 in /usr/local/lib/python3.11/dist-packages (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (5.2.0)
Requirement already satisfied: hpack<4,>=3.0 in /usr/local/lib/python3.11/dist-packages (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (3.0.0)
Using cached httpx-0.13.3-py3-none-any.whl (55 kB)
Using cached httpcore-0.9.1-py3-none-any.whl (42 kB)
Using cached h11-0.9.0-py2.py3-none-any.whl (53 kB)
Installing collected packages: h11, httpcore, httpx
  Attempting uninstall: h11
    Found existing installation: h11 0.14.0
    Uninstalling h11-0.14.0:
      Successfully uninstalled h11-0.14.0
  Attempting uninstall: httpcore
    Found existing installation: httpcore 1.0.7
    Uninstalling httpcore-1.0.7:
      Successfully uninstalled httpcore-1.0.7
  Attempting uninstall: httpx
    Found existing installation: httpx 0.28.1
    Uninstalling httpx-0.28.1:
      Successfully uninstalled httpx-0.28.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
anthropic 0.44.0 requires httpx<1,>=0.23.0, but you have httpx 0.13.3 which is incompatible.
langsmith 0.2.10 requires httpx<1,>=0.23.0, but you have httpx 0.13.3 which is incompatible.
openai 1.59.6 requires httpx<1,>=0.23.0, but you have httpx 0.13.3 which is incompatible.
Successfully installed h11-0.9.0 httpcore-0.9.1 httpx-0.13.3

In [ ]:
from googletrans import Translator


translator = Translator()

def translate_text(text):
    try:
        # Détecter la langue
        detected_lang = translator.detect(text).lang
        # Traduire uniquement si la langue détectée n'est pas déjà l'anglais
        if detected_lang != 'en':
            return translator.translate(text, src=detected_lang, dest='en').text
        else:
            return text
    except Exception as e:
        return f"Error: {e}"

df_description= df_description.apply(translate_text)

display(df_description)

0      This apartment is located on the ground floor ...
1      This apartment is located in Chotrena 1 in a r...
2      This apartment is located in Dyar Ben Mahmoud ...
3      For sale: S+2 apartment with a large terrace, ...
4      For sale to ennasse an S3 apartment on the 5th...
                             ...
574    Error: 'Translator' object has no attribute 'r...
575    Error: 'Translator' object has no attribute 'r...
576    Error: 'Translator' object has no attribute 'r...
577    Error: 'Translator' object has no attribute 'r...
578    Error: 'Translator' object has no attribute 'r...
Name: description, Length: 579, dtype: object

In [ ]:
display(df_description)

0      This apartment is located on the ground floor ...
1      This apartment is located in Chotrena 1 in a r...
2      This apartment is located in Dyar Ben Mahmoud ...
3      For sale: S+2 apartment with a large terrace, ...
4      For sale to ennasse an S3 apartment on the 5th...
                             ...
574    Error: 'Translator' object has no attribute 'r...
575    Error: 'Translator' object has no attribute 'r...
576    Error: 'Translator' object has no attribute 'r...
577    Error: 'Translator' object has no attribute 'r...
578    Error: 'Translator' object has no attribute 'r...
Name: description, Length: 579, dtype: object

In [ ]:
! pip install google-generativeai

Requirement already satisfied: google-generativeai in /usr/local/lib/python3.11/dist-packages (0.8.3)
Requirement already satisfied: google-ai-generativelanguage==0.6.10 in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (0.6.10)
Requirement already satisfied: google-api-core in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (2.19.2)
Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (2.155.0)
Requirement already satisfied: google-auth>=2.15.0 in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (2.27.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (4.25.5)
Requirement already satisfied: pydantic in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (2.10.5)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (4.67.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (4.12.2)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /usr/local/lib/python3.11/dist-packages (from google-ai-generativelanguage==0.6.10->google-generativeai) (1.25.0)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core->google-generativeai) (1.66.0)
Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in /usr/local/lib/python3.11/dist-packages (from google-api-core->google-generativeai) (2.32.3)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth>=2.15.0->google-generativeai) (5.5.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth>=2.15.0->google-generativeai) (0.4.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth>=2.15.0->google-generativeai) (4.9)
Requirement already satisfied: httplib2<1.dev0,>=0.19.0 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client->google-generativeai) (0.22.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client->google-generativeai) (0.2.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client->google-generativeai) (4.1.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic->google-generativeai) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic->google-generativeai) (2.27.2)
Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.10->google-generativeai) (1.69.0)
Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.10->google-generativeai) (1.62.3)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /usr/local/lib/python3.11/dist-packages (from httplib2<1.dev0,>=0.19.0->google-api-python-client->google-generativeai) (3.2.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.11/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.6.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core->google-generativeai) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core->google-generativeai) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core->google-generativeai) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core->google-generativeai) (2024.12.14)

In [ ]:
import os

# Set the Gemini API Key
os.environ["GEMINI_API_KEY"] = ""

In [ ]:
!pip install ratelimit
!pip install tenacity

Requirement already satisfied: ratelimit in /usr/local/lib/python3.11/dist-packages (2.2.1)
Requirement already satisfied: tenacity in /usr/local/lib/python3.11/dist-packages (9.0.0)

In [ ]:
import os
import pandas as pd
import google.generativeai as genai
from ratelimit import limits, sleep_and_retry
import time
import json
import typing_extensions as typing

# Define the response schema
class Amenities(typing.TypedDict):
    garden: typing.Optional[str]
    parking: typing.Optional[str]
    pool: typing.Optional[str]
    beach_view: typing.Optional[str]
    mountain_view: typing.Optional[str]

class PropertyFeatures(typing.TypedDict):
    location: typing.Optional[str]
    city: typing.Optional[str]
    surface: typing.Optional[str]
    rooms: typing.Optional[int]
    bathrooms: typing.Optional[int]
    etat_age: typing.Optional[str]
    amenities: Amenities  
    central_heating: typing.Optional[str]
    air_conditioning: typing.Optional[str]
    elevator: typing.Optional[str]
    floor: typing.Optional[str]

# Configure the API key
genai.configure(api_key=os.environ["GEMINI_API_KEY"])

# Create the model configuration
generation_config = genai.GenerationConfig(
    temperature=1,
    top_p=0.95,
    max_output_tokens=8192,
    response_mime_type="application/json",
    response_schema=list[PropertyFeatures],
)

# Define the model
model = genai.GenerativeModel(
    model_name="gemini-2.0-flash-exp",
    generation_config=generation_config,
)

# Define rate limit (e.g., 3 calls per minute)
RATE_LIMIT_CALLS = 3
RATE_LIMIT_PERIOD = 60  # in seconds

@sleep_and_retry
@limits(calls=RATE_LIMIT_CALLS, period=RATE_LIMIT_PERIOD)
def extract_features_with_limit(description):
    """
    Calls the LLM API with rate limiting to extract features for a single description.
    """
    return extract_features_LLM(description)

def extract_features_LLM(description):
    """
    Function to extract features from a property description in JSON format.
    The function sends the description to an LLM API and returns the structured JSON response.

    Args:
        description (str): The property description to extract features from.

    Returns:
        dict: The extracted features as a JSON-like dictionary.
    """
    prompt = f"""
Extract the following features from the property description in JSON format. Ensure the response is a well-structured JSON object with no redundancy. All keys should have meaningful values or "None" if not mentioned. Use this exact structure:

{{
    "location": "Location of the property (e.g., street or neighborhood)",
    "city": "City or governorate",
    "surface": "Surface area in square meters",
    "rooms": "Number of rooms",
    "bathrooms": "Number of bathrooms",
    "etat_age": "Age or condition of the property (e.g., new, renovated, old)",
    "amenities": {{
        "garden": "Yes/No",
        "parking": "Yes/No",
        "pool": "Yes/No",
        "beach_view": "Yes/No",
        "mountain_view": "Yes/No"
    }},
    "central_heating": "Yes/No",
    "air_conditioning": "Yes/No",
    "elevator": "Yes/No"
    "floor": "Number of the floor if it is the ground floor then put a 0 "
}}

Description: "{description}"

Important:
- If a feature is not mentioned in the description, assign "None".
- Eliminate redundant entries.
- The JSON should be valid and ready to parse programmatically.
"""
    try:
        # Generate content
        response = model.generate_content(prompt, generation_config=generation_config)

        # Extract the first candidate
        if not response.candidates or not response.candidates[0].content.parts:
            raise ValueError("No valid content parts in response.")

        # Extract the text content from the first part
        content_text = response.candidates[0].content.parts[0].text

        # Parse the text as JSON
        return json.loads(content_text)
    except Exception as e:
        print(f"Error during feature extraction: {e}")
        return {"error": str(e)}

def process_dataset(descriptions, output_file="features_dataset.json", batch_size=5):
    """
    Process the dataset in batches while adhering to API request limits.
    """
    if "description" not in descriptions.columns:
        raise ValueError("The dataset must contain a 'Description' column.")

    all_features = {}
    total_batches = -(-len(descriptions) // batch_size)  # Calculate total number of batches

    for i in range(0, len(descriptions), batch_size):
        batch = descriptions.iloc[i:i + batch_size]
        batch_features = {}

        for idx, row in batch.iterrows():
            try:
                description = row['description']
                features = extract_features_with_limit(description)
                batch_features[idx] = features
            except Exception as e:
                print(f"Error processing description {idx}: {e}")
                batch_features[idx] = {"error": str(e)}

        all_features.update(batch_features)

        # Save the results incrementally
        with open(output_file, "w") as file:
            json.dump(all_features, file, indent=4)

        print(f"Processed batch {i // batch_size + 1}/{total_batches}")
        time.sleep(5)

    print(f"Features saved to {output_file}")

# Process the dataset
df_description= pd.DataFrame(df_description)
process_dataset(df_description, output_file="features_dataset.json", batch_size=5)

Error during feature extraction: Unterminated string starting at: line 1408 column 14 (char 19246)
Processed batch 1/116
Error during feature extraction: Expecting ',' delimiter: line 989 column 23 (char 22891)
Error during feature extraction: Expecting property name enclosed in double quotes: line 1360 column 28 (char 22838)
Processed batch 2/116
Processed batch 3/116
Processed batch 4/116
Error during feature extraction: Expecting property name enclosed in double quotes: line 1480 column 5 (char 22886)
Processed batch 5/116
Error during feature extraction: Expecting ',' delimiter: line 953 column 15 (char 20743)
Processed batch 6/116
Error during feature extraction: Unterminated string starting at: line 1142 column 6 (char 22025)
Processed batch 7/116
Error during feature extraction: Unterminated string starting at: line 1071 column 20 (char 20013)
Processed batch 8/116
Error during feature extraction: Expecting property name enclosed in double quotes: line 1478 column 5 (char 26434)
Processed batch 9/116
Error during feature extraction: Expecting value: line 1563 column 1 (char 22855)
Processed batch 10/116
Error during feature extraction: Unterminated string starting at: line 1208 column 19 (char 25129)
Error during feature extraction: Expecting value: line 1411 column 17 (char 22566)
Error during feature extraction: Unterminated string starting at: line 1120 column 18 (char 21126)
Processed batch 11/116
Processed batch 12/116
Processed batch 13/116
Error during feature extraction: Unterminated string starting at: line 1244 column 19 (char 20346)
Error during feature extraction: Expecting property name enclosed in double quotes: line 1113 column 1 (char 21495)
Processed batch 14/116
Error during feature extraction: Expecting property name enclosed in double quotes: line 1094 column 49 (char 22736)
Error during feature extraction: Expecting property name enclosed in double quotes: line 1460 column 1 (char 19780)
Processed batch 15/116
Error during feature extraction: Unterminated string starting at: line 1325 column 15 (char 21033)
Processed batch 16/116
Processed batch 17/116
Processed batch 18/116
Error during feature extraction: Unterminated string starting at: line 1298 column 5 (char 18759)
Processed batch 19/116
Error during feature extraction: Unterminated string starting at: line 1277 column 6 (char 22203)
Error during feature extraction: Expecting property name enclosed in double quotes: line 1142 column 4 (char 21497)
Processed batch 20/116
Error during feature extraction: Unterminated string starting at: line 1240 column 8 (char 23111)
Processed batch 21/116
Error during feature extraction: Expecting property name enclosed in double quotes: line 981 column 1 (char 18615)
Processed batch 22/116
Error during feature extraction: Unterminated string starting at: line 971 column 16 (char 19148)
Processed batch 23/116
Processed batch 24/116
Error during feature extraction: Unterminated string starting at: line 1341 column 16 (char 18819)
Processed batch 25/116
Processed batch 26/116
Processed batch 27/116
Processed batch 28/116
Error during feature extraction: Unterminated string starting at: line 1153 column 16 (char 22441)
Processed batch 29/116
Processed batch 30/116
Error during feature extraction: Unterminated string starting at: line 1248 column 21 (char 22444)
Processed batch 31/116
Error during feature extraction: Unterminated string starting at: line 1425 column 3 (char 22550)
Processed batch 32/116
Processed batch 33/116
Processed batch 34/116
Processed batch 35/116
Error during feature extraction: Unterminated string starting at: line 921 column 20 (char 24926)
Processed batch 36/116
Processed batch 37/116
Processed batch 38/116
Processed batch 39/116
Error during feature extraction: Expecting value: line 1289 column 6 (char 21613)
Processed batch 40/116
Error during feature extraction: Unterminated string starting at: line 1253 column 9 (char 22177)
Processed batch 41/116
Processed batch 42/116
Processed batch 43/116
Error during feature extraction: Unterminated string starting at: line 1407 column 6 (char 21763)
Processed batch 44/116
Processed batch 45/116
Processed batch 46/116
Processed batch 47/116
Error during feature extraction: Unterminated string starting at: line 1338 column 5 (char 21443)
Processed batch 48/116
Processed batch 49/116
Error during feature extraction: Unterminated string starting at: line 1102 column 5 (char 19539)
Processed batch 50/116
Processed batch 51/116
Processed batch 52/116
Processed batch 53/116
Error during feature extraction: Expecting value: line 1328 column 13 (char 20950)
Error during feature extraction: Unterminated string starting at: line 1347 column 6 (char 20494)
Error during feature extraction: Expecting ',' delimiter: line 1175 column 1 (char 24300)
Processed batch 54/116
Error during feature extraction: Unterminated string starting at: line 1226 column 13 (char 29010)
Processed batch 55/116
Processed batch 56/116
Processed batch 57/116
Error during feature extraction: Expecting value: line 1257 column 16 (char 21403)
Processed batch 58/116
Error during feature extraction: Unterminated string starting at: line 1243 column 8 (char 20123)
Error during feature extraction: Expecting property name enclosed in double quotes: line 1113 column 5 (char 19804)
Error during feature extraction: Expecting ',' delimiter: line 1164 column 4 (char 19476)
Processed batch 59/116
Processed batch 60/116
Processed batch 61/116
Processed batch 62/116
Processed batch 63/116
Error during feature extraction: Expecting ',' delimiter: line 1291 column 25 (char 21074)
Processed batch 64/116
Error during feature extraction: Unterminated string starting at: line 1273 column 18 (char 22105)
Processed batch 65/116
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 85)
Error during feature extraction: Unterminated string starting at: line 1192 column 19 (char 23156)
Processed batch 66/116
Error during feature extraction: Unterminated string starting at: line 1199 column 9 (char 20908)
Error during feature extraction: Unterminated string starting at: line 1229 column 5 (char 19387)
Processed batch 67/116
Error during feature extraction: Expecting property name enclosed in double quotes: line 1106 column 3 (char 19173)
Error during feature extraction: Expecting property name enclosed in double quotes: line 1524 column 1 (char 25751)
Error during feature extraction: Expecting ',' delimiter: line 1122 column 5 (char 20745)
Processed batch 68/116
Processed batch 69/116
Error during feature extraction: Unterminated string starting at: line 925 column 19 (char 24325)
Processed batch 70/116
Error during feature extraction: Unterminated string starting at: line 1186 column 19 (char 22396)
Processed batch 71/116
Error during feature extraction: Unterminated string starting at: line 1103 column 19 (char 19472)
Processed batch 72/116
Error during feature extraction: Expecting value: line 1096 column 17 (char 20459)
Error during feature extraction: Expecting property name enclosed in double quotes: line 1281 column 3 (char 18446)
Processed batch 73/116
Error during feature extraction: Unterminated string starting at: line 1192 column 19 (char 19870)
Error during feature extraction: Unterminated string starting at: line 1324 column 19 (char 22158)
Processed batch 74/116
Error during feature extraction: Unterminated string starting at: line 1173 column 15 (char 21139)
Processed batch 75/116
Processed batch 76/116
Processed batch 77/116
Processed batch 78/116
Error during feature extraction: Unterminated string starting at: line 966 column 18 (char 19360)
Processed batch 79/116
Processed batch 80/116
Error during feature extraction: Unterminated string starting at: line 1000 column 21 (char 24323)
Processed batch 81/116
Processed batch 82/116
Processed batch 83/116
Processed batch 84/116
Error during feature extraction: Expecting value: line 1267 column 16 (char 24873)
Processed batch 85/116
Processed batch 86/116
Processed batch 87/116
Error during feature extraction: Expecting ',' delimiter: line 1190 column 1 (char 19412)
Processed batch 88/116
Error during feature extraction: Unterminated string starting at: line 1203 column 14 (char 25444)
Processed batch 89/116
Error during feature extraction: Unterminated string starting at: line 1119 column 17 (char 19746)
Processed batch 90/116
Processed batch 91/116
Processed batch 92/116
Error during feature extraction: Unterminated string starting at: line 1275 column 9 (char 21091)
Processed batch 93/116
Error during feature extraction: Unterminated string starting at: line 1100 column 17 (char 21230)
Processed batch 94/116
Processed batch 95/116
Error during feature extraction: Unterminated string starting at: line 1337 column 17 (char 20501)
Processed batch 96/116
Error during feature extraction: Expecting property name enclosed in double quotes: line 1203 column 1 (char 24573)
Processed batch 97/116
Processed batch 98/116
Processed batch 99/116
Processed batch 100/116
Error during feature extraction: Expecting value: line 960 column 5 (char 23657)
Error during feature extraction: Expecting property name enclosed in double quotes: line 1261 column 1 (char 20604)
Error during feature extraction: Unterminated string starting at: line 1167 column 18 (char 22181)
Processed batch 101/116
Error during feature extraction: Expecting property name enclosed in double quotes: line 1162 column 7 (char 20602)
Processed batch 102/116
Error during feature extraction: Unterminated string starting at: line 1029 column 16 (char 21857)
Processed batch 103/116
Error during feature extraction: Unterminated string starting at: line 1025 column 20 (char 22644)
Processed batch 104/116
Processed batch 105/116
Error during feature extraction: Unterminated string starting at: line 1167 column 18 (char 22180)
Processed batch 106/116
Error during feature extraction: Unterminated string starting at: line 1481 column 20 (char 24002)
Processed batch 107/116
Processed batch 108/116
Error during feature extraction: Expecting ',' delimiter: line 1187 column 17 (char 20816)
Processed batch 109/116
Processed batch 110/116
Processed batch 111/116
Processed batch 112/116
Processed batch 113/116
Error during feature extraction: Unterminated string starting at: line 1040 column 20 (char 18556)
Error during feature extraction: Unterminated string starting at: line 1024 column 15 (char 22418)
Processed batch 114/116
Processed batch 115/116
Processed batch 116/116
Features saved to features_dataset.json

# Processing of the Json file generated

In [ ]:
import json

input_file = "/content/failed_entres.json"
output_file = "failed_attemps.json"

# Template for consolidated data
template = {
    "location": None,
    "city": None,
    "surface": None,
    "rooms": None,
    "bathrooms": None,
    "etat_age": None,
    "amenities": {
        "garden": None,
        "parking": None,
        "pool": None,
        "beach_view": None,
        "mountain_view": None
    },
    "central_heating": None,
    "air_conditioning": None,
    "elevator": None,
    "floor":None
}

def consolidate_objects(data_list):
    """
    Consolidates a list of property objects into a single structured format.

    Args:
        data_list (list): List of property data dictionaries.

    Returns:
        dict: A consolidated dictionary with no redundant information.
    """
    consolidated = {key: None if not isinstance(value, dict) else value.copy() for key, value in template.items()}

    for obj in data_list:
        for key, value in obj.items():
            if isinstance(value, dict):  # Handle nested dictionaries like "amenities"
                if key in consolidated and isinstance(consolidated[key], dict):
                    for sub_key, sub_value in value.items():
                        if sub_value not in [None, "None"]:
                            consolidated[key][sub_key] = sub_value
            else:
                if value not in [None, "None"]:  # Update only non-"None" values
                    consolidated[key] = value

    return consolidated

result = {}

try:
    with open(input_file, "r") as file:
        data = json.load(file)

    # Process each top-level key in the input data
    for key, value in data.items():
        if isinstance(value, list):  # Check if the value is a list of objects
            result[key] = consolidate_objects(value)
        elif isinstance(value, dict) and "error" in value:  # Retain error objects as is
            result[key] = value
        else:
            print(f"Skipping unexpected entry for key {key}: {value}")

    # Export the cleaned JSON to a file
    with open(output_file, "w") as file:
        json.dump(result, file, indent=4)

    print(f"Processed data has been exported to {output_file}")

except json.JSONDecodeError as e:
    print(f"Error loading JSON: {e}")

Processed data has been exported to failed_attemps.json

Flattening Nested Objects

In [ ]:
import json

# Flatten nested dictionaries
def flatten_dict(d, parent_key='', sep='_'):
    """
    Flattens a nested dictionary.

    Args:
        d (dict): The dictionary to flatten.
        parent_key (str): The base key to prepend to the flattened keys.
        sep (str): Separator to use between keys.

    Returns:
        dict: A flattened dictionary.
    """
    items = []
    for k, v in d.items():
        new_key = f"{k}" if parent_key else k
        if isinstance(v, dict):  # If value is a dictionary, recurse
            items.extend(flatten_dict(v, new_key, sep=sep).items())
        else:
            items.append((new_key, v))
    return dict(items)

# Process JSON file
input_file = "/content/failed_attemps.json"
output_file = "failed_attemps.json"

result = {}

try:
    # Load JSON file
    with open(input_file, "r") as file:
        data = json.load(file)

    # Flatten each object in the JSON
    for key, value in data.items():
        if isinstance(value, dict):  # Flatten a single dictionary
            result[key] = flatten_dict(value)
        elif isinstance(value, list):  # Handle list of dictionaries
            result[key] = [flatten_dict(obj) for obj in value]
        else:  # Retain non-dictionary, non-list values as is
            result[key] = value

    # Export the flattened JSON to a file
    with open(output_file, "w") as file:
        json.dump(result, file, indent=4)

    print(f"Flattened data has been exported to {output_file}")

except json.JSONDecodeError as e:
    print(f"Error loading JSON: {e}")

Flattened data has been exported to failed_attemps.json

count the number of entries with an "error" key

In [ ]:
import json

input_file = "/content/final.json"  

try:
    with open(input_file, "r") as file:
        data = json.load(file)

    # Find entries with "error" key
    error_entries = {key: value["error"] for key, value in data.items() if isinstance(value, dict) and "error" in value}

    print(f"Number of entries with 'error': {len(error_entries)}")
    print("Keys with 'error':", list(error_entries.keys()))

except json.JSONDecodeError as e:
    print(f"Error loading JSON: {e}")

Number of entries with 'error': 79
Keys with 'error': ['4', '5', '8', '20', '25', '34', '35', '40', '49', '50', '51', '52', '67', '69', '72', '73', '75', '91', '98', '99', '103', '109', '112', '124', '144', '151', '158', '178', '195', '202', '218', '237', '246', '265', '268', '269', '270', '286', '290', '291', '292', '317', '324', '326', '327', '330', '333', '335', '337', '338', '346', '352', '358', '360', '362', '366', '368', '372', '393', '401', '424', '437', '441', '449', '461', '467', '478', '481', '500', '501', '502', '509', '511', '515', '526', '531', '540', '566', '568']

Clean failed example description from special characters

In [ ]:
import json
import pandas as pd
import re


json_file = "/content/failed_attempts.json"  # Replace with your JSON file path


with open(json_file, "r") as file:
    data = json.load(file)

# Filter out rows where 'index' matches keys with "error"
error_keys = [int(key) for key, value in data.items() if isinstance(value, dict) and "error" in value]
print("Error keys:", error_keys)

# Filter descriptions based on error keys
filtered_descriptions = pd.DataFrame(df_description.loc[df_description.index.isin(error_keys)])


# Remove special characters and emojis using regex
def clean_text(text): 
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"  # emoticons
        "\U0001F300-\U0001F5FF"  # symbols & pictographs
        "\U0001F680-\U0001F6FF"  # transport & map symbols
        "\U0001F700-\U0001F77F"  # alchemical symbols
        "\U0001F780-\U0001F7FF"  # Geometric Shapes Extended
        "\U0001F800-\U0001F8FF"  # Supplemental Arrows-C
        "\U0001F900-\U0001F9FF"  # Supplemental Symbols and Pictographs
        "\U0001FA00-\U0001FA6F"  # Chess Symbols
        "\U0001FA70-\U0001FAFF"  # Symbols and Pictographs Extended-A
        "\U00002702-\U000027B0"  # Dingbats
        "]+",
        flags=re.UNICODE,
    )
    text = emoji_pattern.sub("", text)  # Remove emojis

    # Remove special characters except for basic punctuation
    text = re.sub(r"[^a-zA-Z0-9\s,.!?']", "", text)

    return text

# Clean descriptions
filtered_descriptions = pd.DataFrame(filtered_descriptions["description"].apply(clean_text))

# Display cleaned descriptions
display(filtered_descriptions)

Error keys: [40, 270, 337, 346, 502]

                                           description
40   S2s3 La Soukravente2850dtm2 TTC On vous propos...
270  FB.6251 Contacter notre conseiller en immobili...
337  Menzah 7bis BH Immo met en vente des apparteme...
346  Agence immobilire le carr 9 vous propose  la v...
502  Cette villa est situe dans un quartier rsident...

Try again Gemini

In [ ]:
import os
import pandas as pd
import google.generativeai as genai
from ratelimit import limits, sleep_and_retry
import time
import json
import typing_extensions as typing

# Define the response schema
class Amenities(typing.TypedDict):
    garden: typing.Optional[str]
    parking: typing.Optional[str]
    pool: typing.Optional[str]
    beach_view: typing.Optional[str]
    mountain_view: typing.Optional[str]

class PropertyFeatures(typing.TypedDict):
    location: typing.Optional[str]
    city: typing.Optional[str]
    surface: typing.Optional[str]
    rooms: typing.Optional[int]
    bathrooms: typing.Optional[int]
    etat_age: typing.Optional[str]
    amenities: Amenities  
    central_heating: typing.Optional[str]
    air_conditioning: typing.Optional[str]
    elevator: typing.Optional[str]
    floor: typing.Optional[str]

# Configure the API key
genai.configure(api_key=os.environ["GEMINI_API_KEY"])

# Create the model configuration
generation_config = genai.GenerationConfig(
    temperature=1,
    top_p=0.95,
    max_output_tokens=8192,
    response_mime_type="application/json",
    response_schema=list[PropertyFeatures],
)

# Define the model
model = genai.GenerativeModel(
    model_name="gemini-2.0-flash-exp",
    generation_config=generation_config,
)

# Define rate limit (e.g., 3 calls per minute)
RATE_LIMIT_CALLS = 3
RATE_LIMIT_PERIOD = 60  # in seconds

@sleep_and_retry
@limits(calls=RATE_LIMIT_CALLS, period=RATE_LIMIT_PERIOD)
def extract_features_with_limit(description):
    """
    Calls the LLM API with rate limiting to extract features for a single description.
    """
    return extract_features_LLM(description)

def extract_features_LLM(description):
    """
    Function to extract features from a property description in JSON format.
    The function sends the description to an LLM API and returns the structured JSON response.

    Args:
        description (str): The property description to extract features from.

    Returns:
        dict: The extracted features as a JSON-like dictionary.
    """
    prompt = f"""
Extract the following features from the property description in JSON format. Ensure the response is a well-structured JSON object with no redundancy. All keys should have meaningful values or "None" if not mentioned. Use this exact structure:

{{
    "location": "Location of the property (e.g., street or neighborhood)",
    "city": "City or governorate",
    "surface": "Surface area in square meters",
    "rooms": "Number of rooms",
    "bathrooms": "Number of bathrooms",
    "etat_age": "Age or condition of the property (e.g., new, renovated, old)",
    "amenities": {{
        "garden": "Yes/No",
        "parking": "Yes/No",
        "pool": "Yes/No",
        "beach_view": "Yes/No",
        "mountain_view": "Yes/No"
    }},
    "central_heating": "Yes/No",
    "air_conditioning": "Yes/No",
    "elevator": "Yes/No"
    "floor": "Number of the floor if it is the ground floor then put a 0 "
}}

Description: "{description}"

Important:
- If a feature is not mentioned in the description, assign "None".
- Eliminate redundant entries.
- The JSON should be valid and ready to parse programmatically.
"""
    try:
        # Generate content
        response = model.generate_content(prompt, generation_config=generation_config)

        # Extract the first candidate
        if not response.candidates or not response.candidates[0].content.parts:
            raise ValueError("No valid content parts in response.")

        # Extract the text content from the first part
        content_text = response.candidates[0].content.parts[0].text

        # Parse the text as JSON
        return json.loads(content_text)
    except Exception as e:
        print(f"Error during feature extraction: {e}")
        return {"error": str(e)}

def process_dataset(descriptions, output_file="output.json", batch_size=5):
    """
    Process the dataset in batches while adhering to API request limits.
    """
    if "description" not in descriptions.columns:
        raise ValueError("The dataset must contain a 'Description' column.")

    all_features = {}
    total_batches = -(-len(descriptions) // batch_size)  # Calculate total number of batches

    for i in range(0, len(descriptions), batch_size):
        batch = descriptions.iloc[i:i + batch_size]
        batch_features = {}

        for idx, row in batch.iterrows():
            try:
                description = row['description']
                features = extract_features_with_limit(description)
                batch_features[idx] = features
            except Exception as e:
                print(f"Error processing description {idx}: {e}")
                batch_features[idx] = {"error": str(e)}

        all_features.update(batch_features)

        # Save the results incrementally
        with open(output_file, "w") as file:
            json.dump(all_features, file, indent=4)

        print(f"Processed batch {i // batch_size + 1}/{total_batches}")
        time.sleep(5)

    print(f"Features saved to {output_file}")

# Process the dataset

process_dataset(pd.DataFrame(filtered_descriptions), output_file="failed_entres.json", batch_size=5)

Error during feature extraction: Unterminated string starting at: line 527 column 19 (char 25841)
Error during feature extraction: Unterminated string starting at: line 5 column 16 (char 74)
Error during feature extraction: Unterminated string starting at: line 25 column 18 (char 31921)
Processed batch 1/16
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 51)
Error during feature extraction: Unterminated string starting at: line 5 column 16 (char 66)

ERROR:tornado.access:503 POST /v1beta/models/gemini-2.0-flash-exp:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 1269.76ms

Processed batch 2/16
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 45)
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 59)
Processed batch 3/16
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 53)
Processed batch 4/16
Error during feature extraction: No valid content parts in response.
Error during feature extraction: Unterminated string starting at: line 5 column 16 (char 75)
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 50)
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 45)
Processed batch 5/16
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 71)
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 46)
Processed batch 6/16
Error during feature extraction: Unterminated string starting at: line 20 column 16 (char 30191)
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 48)
Processed batch 7/16
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 86)
Error during feature extraction: Unterminated string starting at: line 5 column 16 (char 70)
Error during feature extraction: Expecting value: line 332 column 2 (char 10601)
Processed batch 8/16
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 65)
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 80)
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 79)
Processed batch 9/16
Error during feature extraction: Unterminated string starting at: line 820 column 18 (char 18217)
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 68)
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 52)
Error during feature extraction: No valid content parts in response.
Processed batch 10/16
Error during feature extraction: No valid content parts in response.
Error during feature extraction: Unterminated string starting at: line 5 column 16 (char 73)
Error during feature extraction: Unterminated string starting at: line 5 column 16 (char 69)
Processed batch 11/16
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 73)
Error during feature extraction: Unterminated string starting at: line 5 column 16 (char 64)
Processed batch 12/16
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 51)
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 50)
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 51)
Error during feature extraction: No valid content parts in response.
Processed batch 13/16
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 62)
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 45)
Processed batch 14/16
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 58)
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 58)
Processed batch 15/16
Error during feature extraction: Unterminated string starting at: line 5 column 16 (char 64)
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 52)
Error during feature extraction: Unterminated string starting at: line 4 column 16 (char 51)
Error during feature extraction: Unterminated string starting at: line 5 column 16 (char 67)
Processed batch 16/16
Features saved to failed_entres.json

To modify the final.json object so that keys corresponding to error entries are replaced with their corresponding info

In [ ]:
import json


final_json_path = "/content/final.json"
failed_attempts_path = "/content/failed_attempts.json"

with open(final_json_path, "r") as final_file:
    final_data = json.load(final_file)

with open(failed_attempts_path, "r") as failed_file:
    failed_data = json.load(failed_file)

'''
error_entries = {key: value["error"] for key, value in final_data.items() if isinstance(value, dict) and "error" in value}'''

# Replace values in final.json with failed_attempts.json where keys match 
for key in error_entries.keys():
    if key in failed_data:
        final_data[key] = failed_data[key] 

# Save the updated final.json
updated_final_json_path = "/content/updated_final.json" 
with open(updated_final_json_path, "w") as updated_file:
    json.dump(final_data, updated_file, indent=4)

print(f"Updated final.json saved to {updated_final_json_path}")

Updated final.json saved to /content/updated_final.json

# Dataset Adjusting

In [3]:
# Drop row 502 it turns out to be a villa
df=df.drop(df.index[502])

In [11]:
# Drop row 14 it turns out to be a 'centre commerciale + appartements' they didn't make it clear
df=df.drop(df.index[14])

In [13]:
# Drop row 121 it turns out to be a 'centre commerciale + appartements' they didn't make it clear
df=df.drop(df.index[121])

In [20]:
# Drop row 207 it turns out to be a 'duplex with 2 APT' they didn't make it clear in turms of each APT surface and Price
df=df.drop(df.index[207])

In [23]:
# Drop row 332 it turns out to be a 'immeuble sale'
df=df.drop(df.index[332])

In [26]:
# Drop row 360 it turns out to be a 'immeuble sale'
df=df.drop(df.index[360])

In [27]:
# Drop row 415 it turns out to be a 'fond de commerce'
df=df.drop(df.index[415])

In [28]:
import pandas as pd


json_file = "/content/updated_final.json"

# Load JSON file into a DataFrame
df_json = pd.read_json(json_file,orient="index")

display(df_json)

,location,city,surface,rooms,bathrooms,etat_age,garden,parking,pool,beach_view,mountain_view,central_heating,air_conditioning,elevator,floor,error
0,None,None,None,3.0,2.0,None,Yes,Yes,No,No,No,None,None,None,0,NaN
1,Chotrena 1,None,None,2.0,1.0,None,No,Yes,No,No,No,Yes,Yes,No,0,NaN
2,Dyar Ben Mahmoud Agba,None,None,3.0,1.0,None,None,Yes,None,None,None,Yes,Yes,None,0,NaN
3,None,None,None,2.0,NaN,None,No,No,No,No,No,No,No,No,1,NaN
4,ennaser,None,148,3.0,2.0,None,None,Yes,None,None,None,None,None,Yes,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
575,Soukra,None,115m²,2.0,1.0,None,No,No,No,No,No,Yes,Yes,No,1,NaN
576,Cité Ennasr,None,None,3.0,2.0,None,No,Yes,No,No,No,Yes,Yes,No,0,NaN
577,Ennasr gardens,None,None,3.0,3.0,new,No,Yes,No,None,None,Yes,Yes,None,3,NaN
578,Ennasr,None,None,3.0,2.0,None,No,Yes,No,No,No,Yes,Yes,No,1,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unterminated string starting at: line 5 column...

In [5]:
# Filter rows where the value in the column is ≤ 30
invalid_rows = df[df["surface"] <= 30]
display(invalid_rows)

,price,transaction,title,city,region,description,surface,bathrooms,rooms
151,140000.0,sale,Appartement a Lafayette a vendre,tunis,tunis,Appartement a Lafayette rue el chem en face du...,0.0,2.0,3
198,180000.0,sale,A vendre un appartement à bardo2,tunis,bardo,#FIRST_HOME_REAL_ESTATE ( #agence_immobilière_...,1.0,1.0,1
387,350000.0,sale,Appartement S+2 au premier étage à L'Aouina,ben arous,megrine,Cet appartement occupe le premier étage d'une ...,0.0,1.0,2
405,680000.0,sale,A vendre un appartement S3 au Lac 3,tunis,tunis,RE/MAX Four Seasons Agence Immobilière -Cartha...,0.1,2.0,3

Compute the mean of the S+3 APT surface

In [6]:
rooms_3_APT = df[(df["rooms"] == "3") & (df["surface"] > 30)]
display(rooms_3_APT)

# Compute the mean of the "surface" column
if "surface" in rooms_3_APT.columns:
    # Ensure the "surface" column is numeric
    rooms_3_APT["surface"] = pd.to_numeric(rooms_3_APT["surface"], errors="coerce")

    mean_surface = round(rooms_3_APT["surface"].mean(),1)
    print(f"The mean surface for apartments with 3 rooms is: {mean_surface}")
else:
    print("The 'surface' column is not in the DataFrame.")

,price,transaction,title,city,region,description,surface,bathrooms,rooms
0,490000.0,sale,S+3 avec jardin à chotrana 1,ariana,chotrana 1,Cet appartement est situé au rez-de-chaussée d...,141.0,3.0,3
5,410000.0,sale,S+3 neuf jamais habité à vendre,ariana,ghazela,Découvrez notre logement confortable de Haut S...,180.0,2.0,3
9,375000.0,sale,A vendre magnifique Duplex boumhel,ben arous,boumhel,Vous êtes à la recherche d’un Appartement Dupl...,152.0,2.0,3
16,270000.0,sale,Un Appartement S+3 de 122 m² à La Nouvelle Medina,ben arous,medina jedida,Cet Appartement est niché au sein d'une réside...,122.0,2.0,3
19,700000.0,sale,A vendre s3 aux jardins de carthage,tunis,jardins de carthage,À Vendre : Appartement S+3 aux jardins de cart...,199.0,3.0,3
...,...,...,...,...,...,...,...,...,...
571,473000.0,sale,"Duplex B02 en S+3 de 154,8 m² au RDC",ariana,ghazela,"Cet appartement est situé au RDC , Il se compo...",154.0,2.0,3
574,339300.0,sale,A VENDRE S+2 SOUKRA,ariana,soukra,Notre agence palmarès immobilière met à la ven...,117.0,1.0,3
576,380000.0,sale,S+3 en Vente à Ennasr 2,ariana,ennasr 2,Cet appartement occupe le rez-de-chaussée d'un...,145.0,2.0,3
577,550000.0,sale,S+3 à Vendre à Jardin d'Ennasr,ariana,ennasr,Cet appartement occupe le troisième étage d’un...,176.0,3.0,3
578,310000.0,sale,S+3 en Vente à Ennasr 2,ariana,ennasr 2,Cet appartement est situé au premier étage d'u...,119.0,2.0,3

The mean surface for apartments with 3 rooms is: 138.7

<ipython-input-6-ca1588aa3711>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rooms_3_APT["surface"] = pd.to_numeric(rooms_3_APT["surface"], errors="coerce")

Compute the mean of the S+2 APT surface

In [7]:
rooms_2_APT = df[(df["rooms"] == "2") & (df["surface"] > 30)]
display(rooms_2_APT)

# Compute the mean of the "surface" column
if "surface" in rooms_2_APT.columns:
    # Ensure the "surface" column is numeric
    rooms_2_APT["surface"] = pd.to_numeric(rooms_2_APT["surface"], errors="coerce")

    mean_surface_2 = round(rooms_2_APT["surface"].mean(),1)
    print(f"The mean surface for apartments with 3 rooms is: {mean_surface_2}")
else:
    print("The 'surface' column is not in the DataFrame.")

,price,transaction,title,city,region,description,surface,bathrooms,rooms
1,380000.0,sale,un s+2 à chotrana 1,ariana,chotrana 1,Cet appartement est situé à chotrana 1 dans un...,100.00,1.0,2
11,255000.0,sale,S+2 haut standing à la nouvelle soukra,ariana,soukra,A vendre un appartement S+2 haut standing sit...,90.00,1.0,2
12,125000.0,sale,a vendre,ben arous,megrine,Un appartement est situé au premier étage d'u...,117.00,1.0,2
13,200000.0,sale,appartement s+2,ben arous,megrine,Cet appartement est situé au premier étage d'u...,75.00,1.0,2
17,120000.0,sale,APPARTEMENT A VENDRE,ariana,ariana,A vendre appartement S+1 à citer takacim borj ...,54.00,1.0,2
...,...,...,...,...,...,...,...,...,...
568,482160.0,sale,"Appartement (B24) en S+2 de 115,19m² au deuxiè...",ariana,chotrana 2,Cet appartement est situé au deuxiéme étage d’...,115.19,1.0,2
569,457043.0,sale,Appartement en S+2 à Boumhal Bel Air,ben arous,boumhel,Explorez la résidence THE GARDEN à Boumhal Bel...,113.73,2.0,2
572,227000.0,sale,Appartement S+1 avec terrasse sur plan à vendr...,ariana,soukra,👀👀Palmarès immobilier met en vente un appartem...,81.00,1.0,2
573,360000.0,sale,S+1 HST AVEC JARDIN A VENDRE A LA SOUKRA,ariana,soukra,👀👀Palmarès immobilier met en vente un appartem...,170.00,1.0,2
575,380000.0,sale,S+2 Sur Plan à La Soukra,ariana,soukra,✅✅Palmarès immobilier met en vente un appartem...,115.00,1.0,2

The mean surface for apartments with 3 rooms is: 106.9

<ipython-input-7-7b683b9f6e29>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rooms_2_APT["surface"] = pd.to_numeric(rooms_2_APT["surface"], errors="coerce")

Check mistaches between the initial Dataset and the description

In [8]:
# Compare the "rooms" column where indices match, handling NaN and non-integer cases
mismatched_indices = []

for idx in df.index:
    if idx in df_json.index:
        room_df = df.at[idx, "rooms"]
        room_json = df_json.at[idx, "rooms"]

        # Convert to integers safely, treating NaN or non-numeric as mismatches
        try:
            room_df = int(room_df) if pd.notna(room_df) else None
            room_json = int(room_json) if pd.notna(room_json) else None
        except ValueError:
            room_df, room_json = None, None

        # Check for mismatches
        if room_df != room_json:
            mismatched_indices.append(idx)
print(mismatched_indices)

[2, 3, 6, 7, 11, 15, 18, 24, 36, 40, 41, 50, 53, 54, 56, 58, 59, 66, 70, 73, 77, 79, 84, 85, 95, 96, 97, 100, 104, 105, 107, 112, 114, 119, 121, 126, 129, 131, 132, 135, 136, 137, 142, 143, 145, 148, 149, 156, 160, 162, 172, 176, 178, 179, 181, 183, 187, 188, 189, 191, 192, 194, 195, 198, 199, 200, 202, 205, 206, 207, 211, 214, 215, 216, 219, 225, 228, 232, 233, 234, 236, 240, 241, 246, 247, 250, 252, 258, 262, 271, 272, 278, 283, 284, 285, 287, 289, 291, 295, 301, 302, 305, 310, 311, 315, 316, 325, 326, 330, 332, 333, 337, 340, 341, 348, 349, 350, 352, 354, 355, 359, 360, 362, 364, 367, 368, 370, 371, 373, 375, 376, 378, 380, 382, 383, 384, 385, 386, 395, 406, 410, 413, 414, 415, 416, 418, 421, 423, 425, 428, 429, 432, 433, 435, 440, 441, 443, 446, 447, 451, 452, 453, 455, 458, 462, 463, 465, 466, 469, 470, 471, 483, 484, 485, 486, 487, 489, 490, 491, 497, 499, 504, 505, 506, 507, 508, 509, 511, 516, 517, 518, 519, 520, 521, 522, 525, 529, 538, 542, 545, 546, 547, 551, 553, 554, 556, 558, 559, 561, 563, 574]

In [29]:
# Vérifier si la colonne 'rooms' contient des valeurs nulles (NaN)
has_null_values = df_json[df_json["rooms"].isna()]

# Afficher les indices des lignes contenant des valeurs nulles dans 'rooms'
mismatched_indices = has_null_values.index.tolist()
print(mismatched_indices)
display(pd.DataFrame(df.loc[mismatched_indices]))

[291, 416, 435, 440, 443, 446, 455, 458, 462, 463, 487, 509, 519, 574, 40]

,price,transaction,title,city,region,description,surface,bathrooms,rooms
291,1116800.0,sale,"Duplex (A05) de 243,58 m² au RDC",ariana,chotrana 2,Cet appartement est situé au RDC d’une résiden...,243.58,2.0,3
416,312800.0,sale,A vendre des appartement à Borej cedria,ben arous,borj cedria,A vendre à Borej cedria prés de hôtel “SOLIMAR...,136.0,1.0,3
435,260000.0,sale,Appartement Neuf (Promotion immobilière) à Med...,ben arous,medina jedida,"A Vendre à Medina Jadida, Des appartement HST ...",107.0,2.0,2
440,235000.0,sale,RÉSIDENCE EN COURS R+2 À La Soukra,ariana,soukra,Darcom-Tunisia La Soukra met à la vente un imm...,62.0,1.0,1
443,210000.0,sale,RÉSIDENCE NEUVE À LA NOUVELLE SOUKRA,ariana,soukra,Darcom-Tunisia La Soukra vous mène à La Nouvel...,77.0,1.0,1
446,850000.0,sale,A VENDRE VILLA A CITE GHAZELA ARIANA,ariana,ghazela,À vendre une villa à Cité Ghazéla Ariana de 70...,707.0,1.0,1
455,118000.0,sale,appartement a mourouj 5 a vendre,ben arous,mourouj 5,"Appartement à vendre à Al Murooj 5, proche de ...",85.0,1.0,2
458,188000.0,sale,a vendre un appartement s1 a l'aouina cité wah...,tunis,aouina,a vendre un appartement s1 a l'aouina cité wah...,77.0,1.0,1
462,247000.0,sale,PROJET R+2 À CHOTRANA 1 LA SOUKRA,ariana,chotrana 1,Darcom-Tunisia La Soukra vous mène à chotrana ...,70.0,1.0,1
463,460000.0,sale,PROJET NEUF R+2 À Soukra,ariana,soukra,Agence immobilière DARCOM TUNISIA vous propose...,49.0,1.0,1
487,299000.0,sale,A vendre à Menzah 7 Bis,ariana,menzah 7,L’Ag. CONTACTimmo vous offre pour la vente une...,115.0,1.0,02
509,750000.0,sale,Immeuble Ramousa à Vendre à Ezzahra,ben arous,ezzahra,Un immeuble sur un terrain de 500 m² situé dan...,500.0,2.0,6
519,1300000.0,sale,A vendre villa Ariana essoghra,ariana,ariana essoughra,Votre agence immobilière Bestimmo vous propose...,468.0,4.0,7
574,339300.0,sale,A VENDRE S+2 SOUKRA,ariana,soukra,Notre agence palmarès immobilière met à la ven...,117.0,1.0,3
40,353400.0,sale,À vendre s2 et S3 neuf à la soukra,ariana,soukra,#S+2/s+3 La Soukra#vente(2850dtm2 TTC) On vous...,124.0,2.0,2

In [14]:
df.at[143, 'surface'] = "135.0"

<ipython-input-14-0bf700812c46>:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '135.0' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.at[143, 'surface'] = "135.0"